services:
  mysql:
    image: mysql:latest
    container_name: shop-mysql
    environment:
      MYSQL_DATABASE: commerce
      MYSQL_USER: commerce
      MYSQL_PASSWORD: commerce
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"